name: Build and Deploy Go App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: nitin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Build Go Binary
        run: |
          GO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o main

        with:
          go-version: '1.22'

      - name: Go build
        run: go build -o master mainfile.go
